enum Phases {
  GREET,
  DEMOGRAPHICS_NAME_1,
  DEMOGRAPHICS_NAME_2,
  DEMOGRAPHICS_SCHOOL,

  PRETEST_QUESTION,
  PRETEST_WRONG,
  PRETEST_CORRECT,
  PRETEST_INTRO,

  PRETEST_RESULT,

  SELECT_CATEGORY_1,
  CATEGORY_ALREADY_SELECTED,

  ANIMALS_INTRO,
  ANIMALS_1,
  ANIMALS_1_CORRECT,
  ANIMALS_1_WRONG,
  ANIMALS_2,
  ANIMALS_2_CORRECT,
  ANIMALS_2_WRONG,
  ANIMALS_RESULT,
  PLACES_INTRO,
  PLACES_1,
  PLACES_1_CORRECT,
  PLACES_1_WRONG,
  PLACES_2,
  PLACES_2_CORRECT,
  PLACES_2_WRONG,
  PLACES_RESULT,

  NUMBERS_INTRO,
  NUMBERS_1,
  NUMBERS_1_CORRECT,
  NUMBERS_1_WRONG,
  NUMBERS_2,
  NUMBERS_2_CORRECT,
  NUMBERS_2_WRONG,
  NUMBERS_RESULT,

  CATEGORIES_END_1,
  CATEGORIES_END_2,
  CATEGORIES_END_CAROUSEL,
  CATEGORIES_END_NO,

  POSTTEST_INTRO,
  POSTTEST_1,
  POSTTEST_1_CORRECT,
  POSTTEST_1_WRONG,
  POSTTEST_2,
  POSTTEST_2_CORRECT,
  POSTTEST_2_WRONG,
  POSTTEST_RESULT,

  CHAT_END,
  CHAT_END_BACK_BUTTON,

  NO_MORE,
}

export default Phases;
