enum Phases {
  GREET,
  DEMOGRAPHICS_NAME_1,
  DEMOGRAPHICS_NAME_2,
  DEMOGRAPHICS_SCHOOL,
  PRETEST_1,
  PRETEST_1_CORRECT,
  PRETEST_1_WRONG,
  PRETEST_2,
  PRETEST_2_CORRECT,
  PRETEST_2_WRONG,
  PRETEST_RESULT,
  SELECT_CATEGORY_1,
}

export default Phases;
