enum Phases {
  GREET,
  DEMOGRAPHICS_NAME_1,
  DEMOGRAPHICS_NAME_2,
  DEMOGRAPHICS_SCHOOL,

  PRETEST_QUESTION,
  PRETEST_WRONG,
  PRETEST_CORRECT,
  PRETEST_INTRO,

  PRETEST_RESULT,

  SELECT_CATEGORY_1,
  CATEGORY_ALREADY_SELECTED,

  DEFINITION_INTRO,
  DEFINITION_INTRO_TAGLISH,
  DEFINITION_INTRO_2,
  DEFINITION_INTRO_2_TAGLISH,
  DEFINITION_INTRO_3,
  DEFINITION_INTRO_4,
  DEFINITION_QUESTION,
  DEFINITION_CORRECT,
  DEFINITION_WRONG,
  DEFINITION_RESULT,

  EXAMPLES_INTRO_1,
  EXAMPLES_INTRO_2,
  EXAMPLES_INTRO_3,
  EXAMPLES_INTRO_4,
  EXAMPLES_INTRO_5,
  EXAMPLES_INTRO_6,
  EXAMPLES_INTRO_7,
  EXAMPLES_QUESTION_INTRO,

  EXAMPLES_QUESTION,
  EXAMPLES_CORRECT,
  EXAMPLES_WRONG,
  EXAMPLES_RESULT,

  CATEGORIES_END_1,
  CATEGORIES_END_2,
  CATEGORIES_END_CAROUSEL,
  CATEGORIES_END_NO,

  POSTTEST_QUESTION,
  POSTTEST_WRONG,
  POSTTEST_CORRECT,
  POSTTEST_INTRO,
  POSTTEST_RESULT,

  CHAT_END,
  CHAT_END_BACK_BUTTON,

  NO_MORE,
}

export default Phases;
