import Question from './types/Question';

export const correctMessages = [
  'Congratulations! Your answer is absolutely correct!',
  "Well done! You've got it right!",
  "Great job! That's the correct answer!",
  "You're absolutely right! Excellent work!",
  'Bravo! Your answer is spot on!',
  'You nailed it! Your answer is correct!',
  'Correctamundo! You got the right answer!',
  "You're on fire! That's the correct answer!",
  'Perfect! Your answer is absolutely correct!',
  "You're absolutely on point! Your answer is correct!",
  "That's correct! You're doing fantastic!",
  "You're crushing it! That's the right answer!",
  "You're spot-on! Your answer is correct!",
  "Fantastic! You've answered correctly!",
  "You're acing it! That's the correct answer!",
  'Impressive! Your answer is correct!',
  "You're a star! That's the right answer!",
  'Absolutely correct! Great job!',
  "You've got it! That's the correct answer!",
  'Spotless! Your answer is correct!',
  "Incredible! You've answered correctly!",
  "You're doing amazing! That's the right answer!",
  'Outstanding! Your answer is correct!',
  "Terrific! You've got it right!",
  "Hooray! That's the correct answer!",
  'Wonderful! Your answer is correct!',
  "You're smashing it! That's the right answer!",
  'Perfecto! Your answer is correct!',
  "Superb! You've answered correctly!",
  "You're doing brilliantly! That's the correct answer!",
  'Excellent! Your answer is correct!',
];

export const expectationMessages = [
  "Let's see if you will get this one right.",
  "Here's a challenge for you. Can you get this right?",
  'Time to test your knowledge. Will you get this one right?',
  'Think carefully. Can you answer this correctly?',
  "Get ready! Let's see if you can answer this right.",
  'This one might be a bit tricky. Can you get it right?',
  "Let's put your skills to the test. Will you answer this correctly?",
  "Challenge accepted? Let's see if you can get this one right.",
  'Time for a brain teaser. Can you answer this correctly?',
  "Ready for a challenge? Let's see if you can get this right.",
  "Here's a question for you. Can you answer it correctly?",
  "Let's see if you've been paying attention. Can you get this right?",
  'This one requires some thinking. Will you answer it correctly?',
  "Let's test your knowledge. Can you get this question right?",
  'Get your thinking cap on. Will you answer this correctly?',
  "Let's see if you're up for the challenge. Can you get this right?",
  "Think you know the answer? Let's see if you're right.",
  'Ready to show off your knowledge? Can you get this question right?',
  'This one might catch you off guard. Can you still answer it correctly?',
  "Let's see if you can crack this question. Can you get it right?",
  'Time for a little quiz. Will you answer this question correctly?',
  "Think you're an expert? Let's see if you can answer this correctly.",
  "Here's a test for you. Can you get this question right?",
  "Ready to put your skills to the test? Let's see if you can answer this correctly.",
  "Let's see if you can solve this one. Can you get it right?",
  "Think you've got what it takes? Can you answer this correctly?",
  "Prepare yourself! Let's see if you can get this question right.",
  'This one requires some focus. Can you answer it correctly?',
  'Ready to prove your knowledge? Can you get this right?',
  "Let's see if you can rise to the challenge. Can you answer this correctly?",
  'Get ready to impress. Can you answer this question correctly?',
];

export const incorrectMessages = [
  "Nope, that's not correct.",
  'Oops, wrong answer. Try again!',
  'Not quite right. Keep going!',
  'Incorrect. Give it another shot!',
  'Wrong answer. Keep trying!',
  "Sorry, that's not correct.",
  'Close, but not quite right.',
  'Not the correct answer. Keep going!',
  "Incorrect. Don't give up!",
  'Wrong answer. Keep on trying!',
  "Nope, that's not it. Try again!",
  'Sorry, incorrect answer.',
  'Almost there, but not quite right.',
  'Not the right answer. Keep trying!',
  'Wrong answer. You can do better!',
  'Incorrect. Give it another go!',
  "Nope, that's not the correct answer.",
  'Oops, wrong answer. Keep trying!',
  'Not quite there. Try again!',
  "Wrong answer. Don't give up!",
  "Sorry, that's not the correct answer.",
  "Close, but it's not the right answer.",
  'Not the correct answer. Keep going!',
  'Incorrect. Keep on trying!',
  'Wrong answer. Give it another shot!',
  "Nope, that's not the correct answer.",
  'Oops, incorrect answer. Try again!',
  'Not quite right. Keep on trying!',
  "Wrong answer. You're getting closer!",
  "Sorry, that's not the right answer.",
  'Close, but not quite there. Keep going!',
];

export const preTestQuestions: Question[] = [
  {
    question: '1/5 + 3/7 =',
    answers: ['22/35'],
  },
  {
    question: '11/10 + 12/5 =',
    answers: ['35/10', '7/2'],
  },
  {
    question:
      'Kevin received 3/4 blocks of chocolate from his mother and another 1/3 block of chocolate from his father. How many blocks of chocolate does he have now?',
    answers: ['13/12', '1 and 1/12 blocks of chocolate'],
  },
];
